Repository RustyYato/generic-field-projection, pull requests merged in 2019-10, with the labels that each got.

#7 Code & comment reformatting
  README.md
  core/src/chain.rs
  core/src/lib.rs
  core/src/macros.rs
  core/src/pin.rs
  core/src/project.rs
  core/src/project/from_mut.rs
  core/src/project/from_pin.rs
  core/src/project/from_ref.rs
  core/src/set.rs
  core/src/set/tuple.rs
  core/tests/test_core.rs
  core/tests/test_set.rs
  derive/src/lib.rs
  derive/tests/simple.rs
Labels: documentation

#10 add no_std feature
  .github/workflows/pr-fmt.yml
  .github/workflows/pr-test-core.yml
  .github/workflows/pr-test.yml
  core/Cargo.toml
  core/src/chain.rs
  core/src/lib.rs
  core/src/pin.rs
  core/src/project.rs
  core/src/project/from_arc.rs
  core/src/project/from_box.rs
  core/src/project/from_mut.rs
  core/src/project/from_pin.rs
  core/src/project/from_rc.rs
  core/src/project/from_ref.rs
  core/tests/test_core.rs
  core/tests/test_set.rs
Labels: action, enhancement

#18 Union
  core/tests/union.rs
  derive/src/lib.rs
  derive/tests/union.rs
Labels: enhancement
