Repository RustyYato/generic-field-projection, pull requests merged in 2020-12, with the labels that each got.

#32 Add inverse project ops
  core/src/lib.rs
  core/tests/inverse.rs
Labels: enhancement

#35 offset-based field
  core/src/chain.rs
  core/src/dynamic.rs
  core/src/lib.rs
  core/src/macros.rs
  core/src/pin.rs
  core/src/project.rs
  core/src/set/tuple.rs
  derive/src/lib.rs
Labels: enhancement

#41 Fix(docs): Fix weird formatting in example docs
  intrusive_collections_examples/README.md
Labels: documentation, enhancement

#42 fix: Moved modules into the 'src' directory.
  intrusive_collections_examples/src/basic_datastructures/mod.rs
  intrusive_collections_examples/src/lessons/01_doubly_linked_list.rs
  intrusive_collections_examples/src/lessons/mod.rs
Labels: bug

#36 Extract from `TypeSet` to a new crate `typsy`
  core/Cargo.toml
  core/src/lib.rs
  core/src/project.rs
  core/src/project/from_arc.rs
  core/src/project/from_box.rs
  core/src/project/from_mut.rs
  core/src/project/from_pin.rs
  core/src/project/from_rc.rs
  core/src/project/from_ref.rs
  core/src/set.rs
  core/src/set/tuple.rs
  core/src/type_list.rs
  core/tests/test_list.rs
  core/tests/union.rs
Labels: enhancement
