Repository RustyYato/generic-field-projection, pull requests merged in 2021-02, with the labels that each got.

#53 resolve doc todos - oliver
  core/src/lib.rs
  derive/src/lib.rs
Labels: bug, documentation, enhancement

#45 Fixed some FIXMEs
  README.md
  core/src/lib.rs
  core/src/pin.rs
  core/src/project.rs
  core/src/project/from_pin.rs
  core/tests/inverse.rs
  core/tests/test_core.rs
  core/tests/test_list.rs
  core/tests/union.rs
  derive/src/lib.rs
  derive/tests/simple.rs
  derive/tests/union.rs
Labels: bug

#40 Fix(doc): Expand on safety docs of `Field`
  .rustfmt.toml
  core/src/lib.rs
Labels: documentation, enhancement
